name: Nachos

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install
        run: npm install
          
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        
      - name: Jest
        run: jest
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:test
